version: '3.9'

services:
  app:
    container_name: 'express-app'
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:  
      - .:/app
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network
    environment:
      - name=value
    depends_on:
      - db
  db:
    container_name: 'db'
    image: postgres:latest
    volumes:
      - ./containers/postgres:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=expressdb


networks:
  app-network:
    driver: bridge